Hardcoded mails
factorysh/minasan pull request #6
Opened 2019-06-17 13:42 UTC by nirae

Set a "last_chance_mail" line in the config.yml file for send a mail even if gitlab is unavailable

2019-06-20 15:01 UTC, athoune requested changes
Viper is only for `cmd` package.

2019-06-20 15:01 UTC, athoune commented on gitlab/gitlab.go
> +	"github.com/spf13/viper"
No `viper` import in code. It's as evil as global variable.

2019-06-21 11:44 UTC, athoune requested changes

2019-06-21 11:44 UTC, athoune commented on minasan/minasan.go
> +func (m *Minasan) Targets(mailName, lastChanceMail string) ([]string, string, string, error) {
`lastChanceMail` is a setting, not an argument. It's belong to `Minasan` struct.

2019-06-21 11:57 UTC, nirae commented
Think it's good!

2019-06-21 12:02 UTC, athoune approved these changes

2019-06-21 12:02 UTC, merged